### PR TITLE
Added option dataTablesExcludePattern

### PR DESCRIPTION
**Pull request by mobilebilly**
Allow using regular expression to blacklist tables to export data from

### CODE REVIEW

**Comment by mobilebilly** [comment]
The extra option will be useful, if we want to script the data of all tables except a few

**Comment by sethreno** [comment]
I don't think this is necessary as you can use regex to negate a match. 

For example `--dataTablesPattern "^(?!Dataset.*)"` will match all tables that don't start with `Dataset`.

**Comment by mobilebilly** [comment]
Hi @sethreno , please reconsider
e.g. if youi want to exclude "DataSet", but not "DataSetInfo", your regex will not work.

**Comment by keith-hall** [comment]
You can still achieve that with `^(?!Dataset(?!info))` or `^(?:(?!Dataset)|(?=DataSetInfo))`

**Comment by mobilebilly** [comment]
Thanks @keith-hall.

@sethreno ,@keith-hall, think about the case that you need to script a database with roughly 1k tables, you have to blacklist 50 tables, some of the tables names could partially match the name of other table names.

I know it is possible to do it with a matching regex, but that will be crazy complex.
in contrast, if we allow a blacklist regex, I can simply put something like
^(ceversion|classevent|dbsysgen|dbaudit|gridqueue|dbtable|dbview|dbcolumn|gridlog|licenseuser)$

**Comment by sethreno** [comment]
@mobilebilly That's a good point. It also reminds me of a [quote by  Jamie Zawinski](http://regex.info/blog/2006-09-15/247).

>  Some people, when confronted with a problem, think "I know, I'll use regular expressions." Now they have two problems.

**Comment by mobilebilly** [comment]
superb!

**Pull request merged**
